# Generated by Django 3.2 on 2021-06-21 02:43

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id_accesorio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('estatus', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'accesorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=1)),
                ('razon_social', models.CharField(max_length=100)),
                ('rut_empresa', models.BigIntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.BigIntegerField(blank=True, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('rut_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('logo_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('favicon', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('divisa_principal', models.CharField(blank=True, max_length=3, null=True)),
                ('divisa_secundaria', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle_orden_de_compra', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_estadia', models.DateField()),
                ('final_estadia', models.DateField()),
                ('monto', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenPedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioAdicional',
            fields=[
                ('id_det_serv_adic', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_servicio_adicional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto_neto', models.BigIntegerField()),
                ('iva', models.BigIntegerField()),
                ('monto_total', models.BigIntegerField()),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
                ('doc_anulado', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.BigIntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('celular', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('pedidos', models.CharField(max_length=1)),
                ('estatus', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('id_estado_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusDocumento',
            fields=[
                ('id_estatus_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estatus_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusOrdenCompra',
            fields=[
                ('id_estatus_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estatus_orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusOrdenPedido',
            fields=[
                ('id_estatus_orden_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estatus_orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusRecepcion',
            fields=[
                ('id_estatus_recep', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estatus_recepcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('muestra_menu', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitacionAccesorio',
            fields=[
                ('id_hab_acce', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'habitacion_accesorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.BigIntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('apelldio_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'huesped',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_de_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto_neto', models.BigIntegerField(blank=True, null=True)),
                ('iva', models.BigIntegerField(blank=True, null=True)),
                ('monto_total', models.BigIntegerField(blank=True, null=True)),
                ('cant_huesped', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id_orden_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
            ],
            options={
                'db_table': 'orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatoSemanal',
            fields=[
                ('id_comedor', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('dia_desde', models.DateField()),
                ('dia_hasta', models.DateField()),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'plato_semanal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('especificacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('stock_critico', models.BigIntegerField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepcionOrdenPedido',
            fields=[
                ('id_registro_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('id_detalle_pedido', models.BigIntegerField()),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'recepcion_orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('reg_cod', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.CharField(blank=True, max_length=1, null=True)),
                ('plato', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.BigIntegerField()),
                ('mostrar_inicio', models.CharField(max_length=1)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'servicio_adicional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoComedor',
            fields=[
                ('id_tipo_comedor', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('precio', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tipo_comedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo_sii', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=40, null=True)),
                ('abreviado', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estatus', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('capacidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tipo_habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('codigo_moneda', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_conversion', models.BigIntegerField()),
                ('valor_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipo_moneda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),

        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_empleado', models.BooleanField(default=False)),
                ('is_proveedor', models.BooleanField(default=False)),
                ('imagen', models.CharField(max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
