# Generated by Django 3.2 on 2021-06-07 15:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_empleado', models.BooleanField(default=False)),
                ('is_proveedor', models.BooleanField(default=False)),
                ('imagen', models.CharField(max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('rut_empresa', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('celular', models.IntegerField(null=True)),
                ('nombre_comercial', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('nombre_empresa', models.CharField(max_length=100)),
                ('logo_empresa', models.CharField(max_length=100, null=True)),
                ('favicon', models.CharField(max_length=100, null=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('rut_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_estadia', models.DateField()),
                ('final_estadia', models.DateField()),
                ('monto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=True)),
                ('nombres', models.CharField(max_length=64)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('rut_empleado', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('celular', models.IntegerField(null=True)),
                ('nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('numero_direccion', models.CharField(max_length=20, null=True)),
                ('pedidos', models.BooleanField(help_text='¿Puede realizar pedidos?')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusOrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),

        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('muestra_menu', models.BooleanField(default=True)),
                ('estado_habitacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.estadohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('fecha_nac', models.DateField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('mostrar_inicio', models.BooleanField(default=False)),
                ('imagen', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('codigo_moneda', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, null=True)),
                ('valor_conversion', models.IntegerField()),
                ('valor_peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.BooleanField(null=True)),
                ('plato', models.IntegerField(null=True)),
                ('detalle_orden_compra', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.detalleordencompra')),
                ('habitacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.habitacion')),
                ('huesped', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.huesped')),
                ('tipo_comedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipocomedor')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_cod', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionOrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('id_detalle_pedido', models.IntegerField()),
                ('estatus_recepcion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.estatusrecepcion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
                ('tipo_producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('dia_desde', models.DateField()),
                ('dia_hasta', models.DateField()),
                ('imagen', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_comedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipocomedor')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('empleado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.empleado')),
                ('estatus_orden_pedido', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.estatusordenpedido')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('monto_neto', models.IntegerField(null=True)),
                ('iva', models.IntegerField(null=True)),
                ('monto_total', models.IntegerField(null=True)),
                ('cantidad_huesped', models.IntegerField()),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('estatus_orden_compra', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.estatusordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='MultiMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.configuracion')),
                ('tipo_moneda', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipomoneda')),
            ],
        ),
        migrations.CreateModel(
            name='HuespedDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.BooleanField(default=False)),
                ('detalle_orden_compra', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.detalleordencompra')),
                ('rut_huesped', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='HabitacionAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.accesorio')),
                ('tipo_habitacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipohabitacion')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipohabitacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipoempleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_orden_compra', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.detalleordencompra')),
                ('servicio_adicional', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.servicioadicional')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden_pedido', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.ordenpedido')),
                ('producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden_compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.ordencompra'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.comuna'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.tipocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
