# Generated by Django 3.2 on 2021-06-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo_sii', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=40)),
                ('abreviado', models.CharField(default='', max_length=3)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('monto_neto', models.IntegerField(blank=True)),
                ('iva', models.IntegerField()),
                ('monto_total', models.IntegerField()),
                ('estado_documento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.estatusdocumento')),
                ('nro_ocompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ordencompra')),
                ('nro_opedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ordenpedido')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipodocumento')),
            ],
        ),
    ]
